---

# Fill these in for each cluster
os_manila_mount_shares: []
os_manila_share_lookup_host: localhost
os_manila_share_lookup_once: true
os_manila_mount_state: mounted
os_manila_mount_opts:
  - x-systemd.device-timeout=30
  - x-systemd.mount-timeout=30
  - noatime
  - _netdev # prevents mount blocking early boot before networking available
  - rw
os_manila_mount_share_info: [] # populated by lookup mode

# CEPH specific defaults
os_manila_mount_ceph_version: pacific # from octopus, alternatively an x.y.z version can be used
os_manila_mount_ceph_rpm_key: https://download.ceph.com/keys/release.asc
os_manila_mount_ceph_release_repo: "https://download.ceph.com/rpm-{{ os_manila_mount_ceph_version }}/el{{ ansible_distribution_major_version }}/noarch/ceph-release-1-1.el{{ ansible_distribution_major_version }}.noarch.rpm"
os_manila_mount_ceph_conf_path: /etc/ceph
