---
- name: Ensure users exist
  openstack.cloud.identity_user:
    auth_type: "{{ os_projects_auth_type }}"
    auth: "{{ os_projects_admin_auth }}"
    region_name: "{{ os_projects_region | default(omit) }}"
    cacert: "{{ os_projects_cacert | default(omit) }}"
    cloud: "{{ os_projects_cloud | default(omit) }}"
    interface: "{{ os_projects_interface | default(omit, true) }}"
    name: "{{ user.name }}"
    description: "{{ user.description | default(omit) }}"
    email: "{{ user.email | default(omit) }}"
    password: "{{ user.password | default(omit) }}"
    domain: "{{ user_domain_id }}"
    state: present
    enabled: true
    wait: true
  when: user.create_user | default(true) | bool
  environment: "{{ os_projects_environment }}"
  vars:
    user_domain_id: "{{ (user.domain in os_projects_domain_to_id.values()) | ternary(user.domain, os_projects_domain_to_id[user.domain]) }}"
  loop_control:
    label: "{{ user.name }}"
