---
- name: Ensure project users exist
  openstack.cloud.identity_user:
    auth_type: "{{ os_projects_auth_type }}"
    auth: "{{ os_projects_admin_auth }}"
    region_name: "{{ os_projects_region | default(omit) }}"
    cacert: "{{ os_projects_cacert | default(omit) }}"
    cloud: "{{ os_projects_cloud | default(omit) }}"
    interface: "{{ os_projects_interface | default(omit, true) }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    email: "{{ item.email | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    # NOTE(bbezak): identity_user looks up default_project in the user domain
    # ('domain'). Omit default_project for cross-domain users to avoid false
    # "No Project found" errors.
    default_project: "{{ (user_domain_id == project_domain_id) | ternary(project.name, omit) }}"
    domain: "{{ user_domain_id }}"
    state: present
    enabled: true
    wait: true
  with_items: "{{ project.users }}"
  when: item.create_user | default(true) | bool
  environment: "{{ os_projects_environment }}"
  vars:
    user_domain_id: "{{ (project.user_domain in os_projects_domain_to_id.values()) | ternary(project.user_domain, os_projects_domain_to_id[project.user_domain]) }}"
    project_domain_id: "{{ (project.project_domain in os_projects_domain_to_id.values()) | ternary(project.project_domain, os_projects_domain_to_id[project.project_domain]) }}"
  loop_control:
    label: "{{ project.name }}: {{ item.name }}"
